# Назва додатку на Fly.io
app = "albireo-daria-96"

# Інструкції збірки
[build]
  dockerfile = "Dockerfile"

# Volume для зберігання даних ephe
[mounts]
  source = "ephe_data"
  destination = "/data/ephe"

# Сервіси для Fly.io
[[services]]
  # Порт, на якому Flask слухає всередині контейнера
  internal_port = 8080
  protocol = "tcp"

  # Відкритий порт для користувачів
  [[services.ports]]
    port = 80
    handlers = ["http"]

  # Автоматичне масштабування (за потреби)
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20