# Назва додатку на Fly.io
app = "albireo-daria-96"

[build]
  dockerfile = "Dockerfile"

# Опційний том для ефемерид
[mounts]
  source = "ephe_data"
  destination = "/data/ephe"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  # Health checks від LB (вони б’ють /, тому варто мати /health)
  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    method = "get"
    path = "/health"