# fly.toml - конфігурація Fly.io для Flask + Gunicorn
app = "albireo-daria-96"

# Дефолтний регіон можна змінити під свої потреби, наприклад "ams" або "fra"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  # Можна додати інші змінні середовища, якщо потрібно
  # EXAMPLE_KEY = "value"

[deploy]
  release_command = ""  # Залишаємо пустим, якщо немає міграцій

[experimental]
  allowed_public_ports = [8080]
  auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = 10000   # 10 секунд
    timeout = 2000     # 2 секунди
    restart_limit = 6