app = "albireo-daria-96"
primary_region = "waw"

[env]
PORT = "8080"
FLASK_APP = "app.py"
FLASK_RUN_HOST = "0.0.0.0"
FLASK_RUN_PORT = "8080"

[build]
# Використовуємо Dockerfile для побудови образу
dockerfile = "Dockerfile"


[http_service]
internal_port = 8080
force_https = true
auto_start_machines = true
auto_stop_machines = "stop"
min_machines_running = 0