app = "albireo-daria-96"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[experimental]
  auto_stop_machines = true
  auto_start_machines = true

[http_service]
  internal_port = 8080
  force_https = true

  [http_service.concurrency]
    type = "requests"
    soft_limit = 20
    hard_limit = 40

  [[http_service.ports]]
    port = 80
    handlers = ["http"]

  [[http_service.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[http_service.tcp_checks]]
    interval = "10s"
    timeout = "2s"