# Назва додатку на Fly.io
app = "albireo-daria-96"

# Інструкції збірки
[build]
  dockerfile = "Dockerfile"

# Том для зберігання ефемерид (збережеться між рестартами)
[mounts]
  source = "ephe_data"
  destination = "/data/ephe"

# Налаштування сервісу
[[services]]
  internal_port = 8080
  protocol = "tcp"

  # Відкриті порти для користувачів
  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  # Автоматичне масштабування
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20