# ====================== Назва додатку ======================
app = "albireo-daria-96"

# ====================== Build ======================
[build]
  dockerfile = "Dockerfile"

# ====================== Том для ефемерид ======================
[mounts]
  source = "ephe-data"
  destination = "/data/ephe"

# ====================== Сервіси ======================
[[services]]
  internal_port = 8080
  protocol = "tcp"

  # Відкриті порти на Fly
  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  # Конкурентність Gunicorn / Flask
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  # Health check для балансувальника
  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    method = "get"
    path = "/health"