# fly.toml для додатку react-astro-app
app = "react-astro-app"

# Вказуємо будувати локальний Dockerfile (не використовуємо готовий образ)
[build]
  dockerfile = "Dockerfile"

# Порт, який слухає додаток
[env]
  PORT = "8080"

# Мережеві налаштування
[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000