# fly.toml для додатку react-astro-app
app = "albireo-daria-96"

# Використовуємо локальний Dockerfile
[build]
  dockerfile = "Dockerfile"

# Змінні оточення
[env]
  PORT = "8080"

# Налаштування мережі та портів
[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  # Перевірка доступності сервісу
  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000