# fly.toml для додатку react-astro-app
app = "albireo-daria-96"

# Використовуємо локальний Dockerfile
[build]
  dockerfile = "Dockerfile"

# Змінні середовища
[env]
  PORT = "8080"

# Налаштування сервісів
[[services]]
  internal_port = 8080
  protocol = "tcp"

  # Порти для HTTP та HTTPS
  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  # TCP перевірка стану
  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000